<a href="https://colab.research.google.com/github/SanghunOh/with_mathematics/blob/main/codes/LinearAlgebra_%ED%96%89%EB%A0%AC%EC%8B%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##행렬 놈(norm) : 행렬/벡터 크기
$ 
\begin{align}
  ||A||=||A||_2 = ||A||_p = \sqrt{∑_{i=1}^N ∑_{j=1}^N a_{ij}^2} \\
  ||x||^2 = ∑_{i=1}^N x_i^2 = x^T x
\end{align}
$

In [ ]:
import numpy as np
matrix_norm = (np.arange(9)-3).reshape((3,3))
matrix_norm

array([[-3, -2, -1],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [ ]:
np.linalg.norm(matrix_norm)

8.306623862918075

##대각합(trace) : 정방행렬에만 정의, 대각원소 합
$
tr(A) = a_{11} + a_{22} + ... + a_{NN} = ∑_{i=1}^N a_{ii}
$

In [ ]:
matrix_eye = np.eye(3)
matrix_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.trace(matrix_eye)

3.0

###트레이스 트릭(trace trick) : 이차 형식(quadratic form) 미분 구할 때 유용.
$
𝑥^𝑇 𝐴 𝑥 = tr(𝑥^𝑇𝐴𝑥) = tr(𝐴𝑥𝑥^𝑇)=tr(𝑥𝑥^𝑇𝐴)
$

In [ ]:
x = (np.arange(6)+2).reshape((2,3))
x

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
np.trace(x.T @ x @ matrix_eye)

139.0

##[행렬식(determinant)](https://datascienceschool.net/02%20mathematics/02.03%20%ED%96%89%EB%A0%AC%EC%9D%98%20%EC%84%B1%EC%A7%88.html#id10) : 벡터 scaling 척도, 정방행렬 A는 det(𝐴)포 표시.
$
\begin{align}
  det(𝐴)=∑_{𝑖=1}^𝑁[(−1)^{𝑖+𝑗0}𝑀_{𝑖,𝑗0}]𝑎_{𝑖,𝑗0}
\end{align}
$
- det(𝐴)=0이면 역수가 존재하지 않으므로 역행렬은 행렬식이 0이 아닌 경우에만 존재

In [ ]:
# Error - x는 정방행렬 아님
# np.linalg.det(x)

In [ ]:
matrix_det_2 = np.array([[2,3], [1,6]])
np.linalg.det(matrix_det_2)

9.000000000000002

In [ ]:
matrix_det = (np.arange(9)+1).reshape(3,3)
matrix_det, matrix_det.T

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]))

In [ ]:
np.linalg.det(matrix_det.T)
# det값이 0이면 full rank가 아님, 
# 즉, 선형변환 과정에서 차원 손실이 일어남을 알 수 있음. 
# column(열)들간에 선형 종속관계가 존재.

0.0