<a href="https://colab.research.google.com/github/SanghunOh/with_mathematics/blob/main/codes/LinearAlgebra_%EC%A2%8C%ED%91%9C%EC%99%80_%EB%B3%80%ED%99%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##선형종속(linearly dependent) : 벡터 선형조합이 영벡터가 되도록 하는 스칼라 계수 𝑐1,𝑐2,…,𝑐𝑁이 존재(계수가 모두 0은 제외)하면 이 벡터들을 말함.
$ 𝑐_1𝑥_1+𝑐_2𝑥_2+⋯+𝑐_𝑁𝑥_𝑁=0 $

In [ ]:
import numpy as np

x1 = np.array([1, 2])
x2 = np.array([3, 3])
x3 = np.array([10, 14])
(2 * x1) + (1 * x2) - (0.5 * x3)

array([0., 0.])

##선형독립(linearly independent) : 벡터들 선형조합이 0이 되기 위해 계수가 모두 0인 것만 존재.
$ 𝑐_1𝑥_1+𝑐_2𝑥_2+⋯+𝑐_𝑁𝑥_𝑁=0→𝑐_1=⋯=𝑐_𝑁=0 $

##선형독립과 선형 연립방정식 : 선형독립 관계를 행렬과 벡터의 곱으로 나타냠
$
𝑐_1𝑥_1+⋯+𝑐_𝑁𝑥_𝑁=
\begin{pmatrix}
𝑥_1 & 𝑥_2& ⋯ & 𝑥_𝑁
\end{pmatrix}
\begin{pmatrix}
𝑐_1 \\ 𝑐_2 \\ ⋮ \\ 𝑐_𝑁
\end{pmatrix}
=𝑋_𝑐
$


###[선형종속인 경우](https://datascienceschool.net/02%20mathematics/03.02%20%EC%A2%8C%ED%91%9C%EC%99%80%20%EB%B3%80%ED%99%98.html#id9) : 특징행렬 𝑋의 열벡터들이 선형종속이거나 선형종속에 가까운 현상을 **다중공선성(multicollinearity)** 함. 

경우 1: 벡터의 개수가 벡터의 차원보다 크면 선형종속이다.
경우 2: 값이 같은 벡터가 있으면 반드시 선형종속이다.

$
\begin{pmatrix}
1 & 5 & 1 \\
3 & 6 & 3 \\
4 & 6 & 4 \\
\end{pmatrix}
$

경우 3: 어떤 벡터가 다른 벡터의 선형조합이면 반드시 선형종속이다.

$ 
𝑥_1=2𝑥_2−3𝑥_3 \\
𝑐_1=−1,𝑐_2=2,𝑐_3=−3 일 때 \\
−1⋅𝑥_1+2𝑥_2−3𝑥_3=0 → 선형종속
$

ex) 국어, 영어, 수학 점수를 각각 별도의 데이터로 포함하면서 세 점수에 의존하는 총점수나 평균을 다시 데이터로 포함.

##랭크(rank) : 열벡터/행벡터 중 서로 독립인 열/행벡터의 최대 개수를 각각 열/행 랭크라 함.
$ 
rank𝐴≤min(𝑀,𝑁) \\
𝐴∈𝐑^{𝑁×𝑀}
$

In [ ]:
rank_X1 = np.array([[1, 3], [2, 4]])
rank_X1, np.linalg.matrix_rank(rank_X1)

(array([[1, 3],
        [2, 4]]), 2)

In [ ]:
rank_X2 = np.array([[1, 3, 5], [2, 3, 7]])
rank_X2, np.linalg.matrix_rank(rank_X2)

(array([[1, 3, 5],
        [2, 3, 7]]), 2)

###풀랭크(full rank) : 랭크가 행의 개수와 열의 개수 중 작은 값과 같은 경우
rank𝐴=min(𝑀,𝑁)

###로우-랭크 행렬(low-rank matrix) : 𝑀 개의 𝑁차원 벡터 𝑥1,𝑥2,⋯,𝑥𝑀을 이용하면 랭크-M 행렬(rank-M matrix)

$
\begin{align}
\begin{pmatrix}
𝑥_1 & 𝑥_2 & ⋯ & 𝑥_𝑀
\end{pmatrix}
\begin{pmatrix}
𝑥^𝑇_1 \\ 𝑥^𝑇_2 \\ ⋮ \\ 𝑥^𝑇_𝑀
\end{pmatrix}
=𝑥_1𝑥^𝑇_1+𝑥_2𝑥^𝑇_2+⋯+𝑥_𝑀𝑥^𝑇_𝑀=
\sum_{𝑖=1}^𝑀 𝑥_𝑖 𝑥_𝑖^T
\end{align}
$
- 특이분해(singular value decomposition)와 PCA(principal component analysis)에 사용

##[벡터공간과 기저벡터](https://datascienceschool.net/02%20mathematics/03.02%20%EC%A2%8C%ED%91%9C%EC%99%80%20%EB%B3%80%ED%99%98.html#id20)