<a href="https://colab.research.google.com/github/SanghunOh/with_mathematics/blob/main/codes/LinearAlgebra_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##연산(Operation) : 스칼라, 벡터, 행렬 데이터를 변형시키는 방법

##전치(transpose) : 행과 열을 바꾸는 연산, 𝑇(or (prime)기호 ′)라는 위첨자(superscript) 사용
$
𝑥→𝑥^T
$
or 
$
𝑥→𝑥^{'} 
$
- Vector \\
$
\begin{align}
  x = \begin{pmatrix}
  x_1 \\ x_2 \\ x_3 \\ ... \\ x_n
  \end{pmatrix}
\end{align} 
$ 
→
$ 
\begin{align}
  x^T = \begin{pmatrix}
  x_1 & x_2 & x_3 & ... & x_n
  \end{pmatrix}
\end{align} 
$
- Matrix \\
$
\begin{align}
       x_{4\times3} = \begin{pmatrix}
        x_{1,1} & x_{1,2} & x_{1,3} \\
        x_{2,1} & x_{2,2} & x_{2,3} \\
        x_{3,1} & x_{3,2} & x_{3,3}  \\
        x_{4,1} & x_{4,2} & x_{4,3} 
        \end{pmatrix}
    \end{align} 
$ 
→
$
\begin{align}
       x_{4\times3}^T = \begin{pmatrix}
        x_{1,1} & x_{1,2} & x_{1,3} \\
        x_{2,1} & x_{2,2} & x_{2,3} \\
        x_{3,1} & x_{3,2} & x_{3,3}  \\
        x_{4,1} & x_{4,2} & x_{4,3} 
        \end{pmatrix}
    \end{align} 
$ 



In [1]:
import numpy as np

In [3]:
matrix_1 = np.array([[11, 21],
       [12, 22],
       [13, 23]])
matrix_1, matrix_1.T, matrix_1.transpose()

(array([[11, 21],
        [12, 22],
        [13, 23]]), array([[11, 12, 13],
        [21, 22, 23]]), array([[11, 12, 13],
        [21, 22, 23]]))

In [4]:
# 1차원 ndarray는 전치 연산이 정의되지 않음
vector_1 = np.array([5.1, 3.5, 1.4, 0.2])
vector_1, vector_1.T

(array([5.1, 3.5, 1.4, 0.2]), array([5.1, 3.5, 1.4, 0.2]))

###해보기 
1. $(matirix^T)^T$를 해 보세요
2. 붓꽃 예제 일부를 transpose 해 보세요.

In [5]:
from sklearn.datasets import load_iris  # 사이킷런 패키지

iris = load_iris()  # 데이터 로드
iris.data[0:3, :].T  # 첫 번째 꽃의 데이터

array([[5.1, 4.9, 4.7],
       [3.5, 3. , 3.2],
       [1.4, 1.4, 1.3],
       [0.2, 0.2, 0.2]])

##행렬의 다른 형태 표기 및 작성법(concatenated)
$
\begin{align}
  X = \begin{pmatrix}
    col_1 \\ col_2 \\ col_3 \\ ... \\ col_M
  \end{pmatrix}
\end{align} 
$ 
=
$ 
\begin{align}
  \begin{pmatrix}
  row_1^T & row_2 & row_3^T & ... & row_N^T
  \end{pmatrix}
\end{align} 
$

$
X ∈ R^{N×M} \\
c_i ∈ R^{N×1} (i = 1, ..., M) \\
r_j^T \in R^{1×M} (j = 1, ..., N) 
$

In [8]:
# concatenate 하면 아래 예는 모두 같음
matrix_2 = np.array([[1,2,3],
                     [4,5,6]])
matrix_2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
row_1 = np.array([[1], [4]])
row_2 = np.array([[2], [5]])
row_3 = np.array([[3], [6]])
# row_1.shape, row_2.shape, row_3.shape
concatenated_rows = np.concatenate([row_1, row_2, row_3], axis=1)
concatenated_rows

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
row_1 = np.array([[1], [2], [3]])
row_2 = np.array([[4], [5], [6]])
concatenated_rows = np.concatenate([row_1.T, row_2.T], axis=0)
concatenated_rows

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.diag(concatenated_rows,k=1)

array([2, 6])

##특수한 형태

###영벡터(zeros-vector) : 모든 원소가 0인 𝑁차원 벡터
$
\begin{align}
  0_N = 0 = \begin{pmatrix}
  0_1 \\ 0_2 \\ 0_3 \\ ... \\ 0_n
  \end{pmatrix}
\end{align} 
$ 

$ 0 ∈ R^{N×1} $

In [27]:
zeros_vector = np.zeros((3, 1))
zeros_vector, zeros_vector.shape

(array([[0.],
        [0.],
        [0.]]), (3, 1))

In [28]:
zeros_vector * row_1

array([[0.],
       [0.],
       [0.]])

In [29]:
zeros_vector + row_1

array([[1.],
       [2.],
       [3.]])

###일벡터(ones-vector) : 모든 원소가 1인 𝑁차원 벡터
$
\begin{align}
  1_N = 1 = \begin{pmatrix}
  1_1 \\ 1_2 \\ 1_3 \\ ... \\ 1_n
  \end{pmatrix}
\end{align} 
$ 

$ 1 ∈ R^{N×1} $

In [30]:
ones_vector = np.ones((3, 1))
ones_vector, ones_vector.shape

(array([[1.],
        [1.],
        [1.]]), (3, 1))

In [31]:
ones_vector * row_1

array([[1.],
       [2.],
       [3.]])

In [32]:
ones_vector + row_1

array([[2.],
       [3.],
       [4.]])

###정방행렬(square matrix) : 행 개수와 열 개수가 같은 행렬, 선형 변환 등에 사용
$
\begin{align}
       x_{3\times3} = \begin{pmatrix}
        x_{1,1} & x_{1,2} & x_{1,3} \\
        x_{2,1} & x_{2,2} & x_{2,3} \\
        x_{3,1} & x_{3,2} & x_{3,3} 
        \end{pmatrix}
    \end{align} 
$ 

$N = M$

In [35]:
matrix_square = np.arange(9).reshape(3,3)
matrix_square

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

###대칭행렬(symmetric matrix) : 전치행렬과 원래의 행렬이 같은 행렬, 정방행렬만 가능.
$S^T = S$

$S ∈ R^{N × N} $

In [66]:
matrix_symmetric_1 = np.array([[0, 1, 2],
                              [1, 4, 5],
                              [2, 5, 8]])
matrix_symmetric_1.shape

(3, 3)

In [67]:
matrix_symmetric_1 == matrix_symmetric_1.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [58]:
matrix_square

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
matrix_triu = np.triu(matrix_square)
matrix_triu, matrix_triu.T

(array([[0, 1, 2],
        [0, 4, 5],
        [0, 0, 8]]), array([[0, 0, 0],
        [1, 4, 0],
        [2, 5, 8]]))

In [71]:
matrix_triu == matrix_triu.T

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [68]:
matrix_symmetric = matrix_triu.copy()
matrix_symmetric += matrix_triu.T - np.diag(matrix_triu.diagonal())
matrix_symmetric

array([[0, 1, 2],
       [1, 4, 5],
       [2, 5, 8]])

In [ ]:
matrix_symmetric == matrix_symmetric.TT

###대각행렬(diagonal matrix) : 모든 비대각 요소가 0인 행렬
- 주 대각(main diagonal) : 행과 열이 같은 위치
- 비대각(off-diagonal) : 대각 위치에 있지 않은 것들

$
\begin{align}
  D_{n, m} = \begin{pmatrix}
  d_{1,1} & 0_{1,2} & ... & 0_{1,n} \\
  0_{2,1} & d_{2,2} & ... & 0_{2,n} \\
  0_{3,1} & 0_{3,2} & ... & 0_{3,n}  \\
  ... & ... & ... & ...  \\
  0_{m,1} & 0_{m,2} & ... & d_{m,n} \\
  0_{m+1,1} & 0_{m+1,2} & ... & 0_{m+1,n+1}  \\
  \end{pmatrix}
\end{align} 
$ 

$ 𝑥 ∈ 𝐑^{n \times m} $ 

In [36]:
matrix_diagonal = np.diag([1, 2, 3])
matrix_diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [47]:
zero_row = np.array([0., 0., 0.])
zero_row

array([0., 0., 0.])

In [48]:
matrix_diagonal_concated = np.vstack([matrix_diagonal, zero_row])
matrix_diagonal_concated

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.],
       [0., 0., 0.]])

###항등행렬(identity matrix) : 대각행렬 중에서 모든 대각성분 값이 1인 대각행렬
$
\begin{align}
  I_{n, m} = \begin{pmatrix}
  1_{1,1} & 0_{1,2} & ... & 0_{1,n} \\
  0_{2,1} & 1_{2,2} & ... & 0_{2,n} \\
  0_{3,1} & 0_{3,2} & ... & 0_{3,n}  \\
  ... & ... & ... & ...  \\
  0_{m,1} & 0_{m,2} & ... & 1_{m,n} \\
  0_{m+1,1} & 0_{m+1,2} & ... & 0_{m+1,n+1}  \\
  \end{pmatrix}
\end{align} 
$ 

$ I ∈ 𝐑^{n \times m} $ 

In [49]:
matrix_identity = np.identity(3)
matrix_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
matrix_eye = np.eye(N=3, M=5, k=-1, dtype=np.int8)
matrix_eye

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]], dtype=int8)