<a href="https://colab.research.google.com/github/SanghunOh/with_mathematics/blob/main/codes/LinearAlgebra_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%98%95%ED%83%9C%EA%B0%84%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###벡터와 행렬도 숫자처럼 덧셈, 뺄셈, 곱셈 등의 연산 가능, 사칙연산과 다른 점 이해

##벡터/행렬 덧셈과 뺄셈 : 같은 크기를 가진 두 개 벡터나 행렬이 조건. 원소끼리 연산을 요소별(element-wise) 연산이라 함.
- Vector \\
$
\begin{align}
  x = \begin{pmatrix}
  1 \\ 2 \\ 3 
  \end{pmatrix}
  , y = \begin{pmatrix}
  4 \\ 6 \\ 8 
  \end{pmatrix}
\end{align} 
$ 
  - x - y \\
$
\begin{align}
  x = \begin{pmatrix}
  1 \\ 2 \\ 3 
  \end{pmatrix}
  + y = \begin{pmatrix}
  4 \\ 6 \\ 8 
  \end{pmatrix}
  = \begin{pmatrix}
  1-4 \\ 2-6 \\ 3-8 
  \end{pmatrix}
  = \begin{pmatrix}
  -3 \\ -4 \\ -5 
  \end{pmatrix}
\end{align} 
$ 
- Matrix 
  - x - y

In [9]:
import numpy as np
vector_1 = np.arange(3).reshape(1,-1)
vector_2 = np.arange(start=4,stop=9,step=2).reshape(1,-1)

vector_1, vector_2

(array([[0, 1, 2]]), array([[4, 6, 8]]))

In [10]:
vector_1 + vector_2

array([[ 4,  7, 10]])

In [11]:
vector_1 - vector_2

array([[-4, -5, -6]])

In [16]:
matrix_1 = np.arange(6).reshape(2,-1)
matrix_2 = np.arange(start=7,stop=19,step=2).reshape(2,-1)
matrix_1, matrix_2

(array([[0, 1, 2],
        [3, 4, 5]]), array([[ 7,  9, 11],
        [13, 15, 17]]))

In [17]:
matrix_1 - matrix_2

array([[ -7,  -8,  -9],
       [-10, -11, -12]])

In [18]:
matrix_1 + matrix_2

array([[ 7, 10, 13],
       [16, 19, 22]])

##스칼라와 벡터/행렬의 곱셈
https://datascienceschool.net/02%20mathematics/02.02%20%EB%B2%A1%ED%84%B0%EC%99%80%20%ED%96%89%EB%A0%AC%EC%9D%98%20%EC%97%B0%EC%82%B0.html#id3