<a href="https://colab.research.google.com/github/SanghunOh/with_mathematics/blob/main/codes/LinearAlgebra_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##[선형조합(linear combination)](https://datascienceschool.net/02%20mathematics/02.02%20%EB%B2%A1%ED%84%B0%EC%99%80%20%ED%96%89%EB%A0%AC%EC%9D%98%20%EC%97%B0%EC%82%B0.html#id5) : 벡터/행렬에 스칼라값을 곱한 후 더하거나 뺀 것, 선형조합해도 크기는 변하지 않음.
$ 𝑐_1𝑥_1+𝑐_2𝑥_2+𝑐_3𝑥_3+⋯+𝑐_𝐿𝑥_𝐿=𝑥 $

$ 𝑐_1𝐴_1+𝑐_2𝐴_2+𝑐_3𝐴_3+⋯+𝑐_𝐿𝐴_𝐿=𝐴 $

$ 𝑐_1,𝑐_2,…,𝑐_𝐿∈𝐑 $ 

$ 𝑥_1,𝑥_2,…,𝑥_𝐿,𝑥∈𝐑^𝑀 $ 

$ 𝐴_1,𝐴_2,…,𝐴_𝐿,𝐴∈𝐑^{𝑀×𝑁} $

##선형회귀 모형(linear regression model) : 독립변수 𝑥에서 종속변수 𝑦를 예측하는 방법 중 하나.
$ \hat{y}=𝑤_1𝑥_1+⋯+𝑤_𝑁𝑥_𝑁 = w^Tx$

### ex) 아파트 값 예측.
- 면적이 1𝑚^2 당 가격은 500만원 증가.
- 층수가 1층 당 가격은 200만원 증가.
- 한강 보이는 곳은 1,000만원 프리미엄.

$
\begin{align}
  𝑦̂ =500𝑥_1+200𝑥_2+1000𝑥_3 = 
  \begin{pmatrix}
  500 & 200 & 1000
  \end{pmatrix}
  \begin{pmatrix}
  x_{1,1} \\ x_{1,2} \\ x_{1,3}
  \end{pmatrix}
  = w^Tx
\end{align} 
$ 

###단점 : 비선형적인 현실 세계의 데이터를 잘 예측하지 못함. 
ex) 아파트 값 예측과 같이 각 항목 따라 단순 비례하지 않음

###가중합(weighted sum) : 어떤 가중치 값을 곱한 후 이 곱셈 결과들을 다시 합한 것.
$ x=(𝑥_1,⋯,𝑥_𝑁)^T, 𝑤=(𝑤_1,⋯,𝑤_𝑁)^T $이면,

$ 𝑤_1𝑥_1+⋯+𝑤_𝑁𝑥_𝑁=
\begin{align} \sum_{𝑖=1}^𝑁𝑤_𝑖 𝑥_𝑖 \end{align} $이다

$
\begin{align}
  \sum_{𝑖=1}^𝑁𝑤_𝑖 𝑥_𝑖 = 
    \begin{pmatrix}
    w_1 & w_2 & ... & w_N
    \end{pmatrix}
    \begin{pmatrix}
    x_1 \\ x_2 \\ ... \\ x_N
    \end{pmatrix}
\end{align} 
= u
$ 


In [1]:
import numpy as np

weights = np.array([0.5, 0.3, 0.1, 0.08, 0.02])
values = np.arange(10).reshape(5, -1)
weights.shape, values.shape

((5,), (5, 2))

In [2]:
np.dot(weights, values), weights @ values

(array([1.64, 2.64]), array([1.64, 2.64]))

####Ex) A, B, C 세 회사의 주식은 각각 80만원, 30만원, 40만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하기.

In [3]:
vector_w = np.array([[80], [30], [40]])
vector_x = np.array([[3], [4], [5]])
vector_w.T.shape, vector_x.shape

((1, 3), (3, 1))

In [4]:
vector_w.T @ vector_x

array([[560]])

###다중 가중합 계산
$
\begin{align}
  \hat{y} = 
    \begin{pmatrix}
    \hat{y}_1 \\ \hat{y}_2 \\ ... \\ \hat{y}_M
    \end{pmatrix}
    =
    \begin{pmatrix}
      w_1x_{1,1} + w_2x_{1,2}+ ...+w_Nx_{1,N} \\ 
      w_2x_{2,1} + w_2x_{2,2}+ ...+w_Nx_{2,N} \\ 
      : \\ 
      w_1x_{M,1} + w_2x_{M,2}+ ...+w_Nx_{M,N} \\ 
    \end{pmatrix}
\end{align} 
$

$
\begin{align}
  &= 
    \begin{pmatrix}
      x_{1,1} & x_{1,2} & ... & x_{1,N} \\ 
      x_{2,1} & x_{2,2} & ... & x_{2,N} \\ 
      : & : & : & : \\ 
      x_{M,1} & x_{M,2} & ... & x_{M,N} \\ 
    \end{pmatrix}
    \begin{pmatrix}
      w_1 \\ w_2 \\ : \\ w_M
    \end{pmatrix}
\end{align} 
= Xw
$ 

In [5]:
features = np.arange(20).reshape(4,-1)
weights = weights.reshape(5,-1)
features.shape, weights.shape

((4, 5), (5, 1))

In [6]:
y_hat = features @ weights
y_hat

array([[ 0.82],
       [ 5.82],
       [10.82],
       [15.82]])

###가중평균(weighted average) : 가중합의 가중치값을 전체 가중치값 합으로 나누는 것.
$
\begin{align}
  \bar{x} = \frac{1}{N} \sum_{𝑖=1}^𝑁𝑥_𝑖 = \frac{1}{𝑁}1^𝑇_𝑁𝑥
\end{align} 
$ 

In [7]:
x = np.arange(10)
N = len(x)

np.ones(N) @ x / N, x.mean()

(4.5, 4.5)

####Ex) 대학 평균 성적 계산 : 1학점과 3학점 과목의 점수가 A 학생이 각각 100점, 60점이면 학점
$ 
\begin{align}
  \frac{1}{1+3}×100+ \frac{3}{1+3}×60=70 
\end{align}
$

In [8]:
each_score_weighteds = np.array([[1], [3]])
each_scores = np.array([[100], [60]])
weighted_total = each_score_weighteds.sum()
each_scores, each_score_weighteds, weighted_total, 

(array([[100],
        [ 60]]), array([[1],
        [3]]), 4)

In [9]:
each_score_weighteds.T @ each_scores / weighted_total, each_scores.mean()

(array([[70.]]), 80.0)

####Ex) 위 조건으로 A 학생이 100점/60점이면 학점, B학생이 95점/75점, C학생이 85점/70점인 경우 각각 학점 구하기. 


In [10]:
each_scores = np.array([[100, 60]
                        ,[95, 75]
                        ,[85, 70]])
each_score_weighteds.shape, each_scores.shape

((2, 1), (3, 2))

In [11]:
each_scores @ each_score_weighteds / weighted_total, each_scores.mean(axis=1)

(array([[70.  ],
        [80.  ],
        [73.75]]), array([80. , 85. , 77.5]))

##[잔차(residual)](https://datascienceschool.net/02%20mathematics/02.02%20%EB%B2%A1%ED%84%B0%EC%99%80%20%ED%96%89%EB%A0%AC%EC%9D%98%20%EC%97%B0%EC%82%B0.html#id29) : 선형 회귀분석 후 예측치와 실제값(target) 차이, 때론 오차(Error)라고도 함.
$ 𝑒_i=𝑦_𝑖−𝑦̂_𝑖=𝑦_𝑖−𝑤^𝑇𝑥_𝑖 $


###잔차 제곱함(RSS: Residual Sum of Squares) : 잔차 전체 크기
$
\begin{align}
  ∑_{i=1}^N e_i^2 = ∑_{i=1}^N (𝑦_𝑖−𝑤^𝑇𝑥_𝑖)^2=𝑒^𝑇𝑒=(𝑦−𝑋𝑤)^𝑇(𝑦−𝑋𝑤)
\end{align} 
$ 


###[이차형식(Quadratic Form)](https://datascienceschool.net/02%20mathematics/02.02%20%EB%B2%A1%ED%84%B0%EC%99%80%20%ED%96%89%EB%A0%AC%EC%9D%98%20%EC%97%B0%EC%82%B0.html#id32) : ‘행벡터 × 정방행렬 × 열벡터’의 형식 구성
$
\begin{align}
  𝑥^𝑇𝐴𝑥=∑_{i=1}^N∑_{𝑗=1}^𝑁 𝑎_{𝑖,𝑗} 𝑥_𝑖 𝑥_𝑗(2.2.85)
\end{align}
$