<a href="https://colab.research.google.com/github/SanghunOh/with_mathematics/blob/main/codes/LinearAlgebra_%ED%96%89%EB%A0%AC%EA%B0%84%EA%B3%B1%EC%85%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##행렬과 행렬 곱셈 : 결과는 행렬
$𝐶=𝐴𝐵→𝑐_{𝑖𝑗}=𝑎^𝑇_𝑖𝑏_𝑗 일려면\\
조건은 𝐴∈𝐑^{𝑁×𝐿},𝐵∈𝐑^{𝐿×𝑀}→𝐴𝐵∈𝐑^{𝑁×𝑀}$

Ex) 행렬 2×3와 3×2 곱 ⇒ 2×2 

$ 
\begin{align}
  \begin{pmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
  \end{pmatrix}
  \begin{pmatrix}
    b_{11} & b_{12}\\
    b_{21} & b_{22}\\
    b_{31} & b_{32}\\
  \end{pmatrix}
  =
  \begin{pmatrix}
    (a_{11}b_{11}+a_{12}b_{21}+a_{13}b_{31}) & (a_{11}b_{12}+a_{12}b_{22}+a_{13}b_{32})\\
    (a_{21}b_{11}+a_{22}b_{21}+a_{23}b_{31}) & (a_{21}b_{12}+a_{22}b_{22}+a_{23}b_{32})\\
  \end{pmatrix}
\end{align} 
$ 


In [ ]:
import numpy as np

matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
matrix_B = np.array([[1, 2], [3, 4], [5, 6]])
matrix_result = matrix_A @ matrix_B
matrix_result, matrix_result.shape

(array([[22, 28],
        [49, 64]]), (2, 2))

###응용)인공신경망의 기본 구조
$ 
\begin{align}
  \begin{pmatrix}
    \hat{y_1} \\
    \hat{y_2} \\
  \end{pmatrix}
  =
  \begin{pmatrix}
    w_{11} & w_{12} & w_{13}\\
    w_{21} & w_{22} & w_{23}\\
  \end{pmatrix}
  \begin{pmatrix}
    x_{11} \\ x_{12} \\ x_{13}\\
  \end{pmatrix}
\end{align} \\
\hat{y} = Wx
$ 


##일반 행렬 교환 법칙과 분배 법칙

In [ ]:
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])
matrix_C = np.array([[9, 8], [7, 6]])

###교환 법칙 : 성립하지 않음
$ 𝐴𝐵≠𝐵𝐴 $

In [ ]:
matrix_A @ matrix_B, matrix_B @ matrix_A

(array([[19, 22],
        [43, 50]]), array([[23, 34],
        [31, 46]]))

###분배 법칙
$
𝐴(𝐵+𝐶)=𝐴𝐵+𝐴𝐶 \\
(𝐴+𝐵)𝐶=𝐴𝐶+𝐵𝐶
$

In [ ]:
matrix_A @ (matrix_B + matrix_C), (matrix_A @ matrix_B) + (matrix_A @ matrix_C)

(array([[42, 42],
        [98, 98]]), array([[42, 42],
        [98, 98]]))

In [ ]:
(matrix_A + matrix_B) @ matrix_C, (matrix_A @ matrix_C) + (matrix_B @ matrix_C)

(array([[110,  96],
        [174, 152]]), array([[110,  96],
        [174, 152]]))

##전치 행렬 분배와 교환 법칙

###분배법칙
$ (𝐴+𝐵)^𝑇=𝐴^𝑇+𝐵^𝑇 $

In [ ]:
(matrix_A + matrix_B).T, matrix_A.T @ matrix_B.T

(array([[ 6, 10],
        [ 8, 12]]), array([[23, 31],
        [34, 46]]))

###연습문제
https://datascienceschool.net/02%20mathematics/02.02%20%EB%B2%A1%ED%84%B0%EC%99%80%20%ED%96%89%EB%A0%AC%EC%9D%98%20%EC%97%B0%EC%82%B0.html#id19
