<a href="https://colab.research.google.com/github/SanghunOh/with_mathematics/blob/main/codes/LinearAlgebra_%EB%82%B4%EC%A0%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##선형조합(linear combination) : 벡터/행렬에 스칼라값을 곱한 후 더하거나 뺀 것, 선형조합해도 크기는 변하지 않음.
$ 𝑐_1𝑥_1+𝑐_2𝑥_2+𝑐_3𝑥_3+⋯+𝑐_𝐿𝑥_𝐿=𝑥 $

$ 𝑐_1𝐴_1+𝑐_2𝐴_2+𝑐_3𝐴_3+⋯+𝑐_𝐿𝐴_𝐿=𝐴 $

$ 𝑐_1,𝑐_2,…,𝑐_𝐿∈𝐑 $ 

$ 𝑥_1,𝑥_2,…,𝑥_𝐿,𝑥∈𝐑^𝑀 $ 

$ 𝐴_1,𝐴_2,…,𝐴_𝐿,𝐴∈𝐑^{𝑀×𝑁} $

##내적(inner product) : 두 벡터 곱셈이며 결과는 스칼라값, 닷 프로덕트(dot product)라고도 함.
$ 𝑥⋅𝑦=<𝑥,𝑦>=𝑥^𝑇𝑦 $
- 내적 조건 1 : 두 벡터의 차원(길이)이 같아햐 함.
- 내적 조건 2 : 앞은 행 벡터이고 뒤는 열 벡터여야 함.

$
\begin{align}
  𝑥^𝑇𝑦 = \begin{pmatrix}
  1 & 2 & 3
  \end{pmatrix}
  \begin{pmatrix}
  4 \\ 5 \\ 6
  \end{pmatrix}
\end{align} 
= 1⋅4+2⋅5+3⋅6=32
$ 


In [2]:
import numpy as np

vector_1 = np.array([[1], [2], [3]])
vector_2 = np.array([[4], [5], [6]])

vector_1.T @ vector_2, np.dot(vector_1.T, vector_2)

(array([[32]]), array([[32]]))

In [3]:
vector_1 = np.array([1, 2, 3])
vector_2 = np.array([4, 5, 6])

vector_1 @ vector_2, np.dot(vector_1, vector_2)

(32, 32)

In [7]:
vector_3 = np.array([7, 8, 9])
# error
# vector_1 @ vector_2 @ vector_3, np.dot(vector_1, vector_2, vector_3)

###가중합(weighted sum) : 어떤 가중치 값을 곱한 후 이 곱셈 결과들을 다시 합한 것.
$ x=(𝑥_1,⋯,𝑥_𝑁)^T, 𝑤=(𝑤_1,⋯,𝑤_𝑁)^T $이면,

$ 𝑤_1𝑥_1+⋯+𝑤_𝑁𝑥_𝑁=
\begin{align} \sum_{𝑖=1}^𝑁𝑤_𝑖 𝑥_𝑖 \end{align} $이다

$
\begin{align}
  \sum_{𝑖=1}^𝑁𝑤_𝑖 𝑥_𝑖 = 
    \begin{pmatrix}
    w_1 & w_2 & ... & w_N
    \end{pmatrix}
    \begin{pmatrix}
    x_1 \\ x_2 \\ ... \\ x_N
    \end{pmatrix}
\end{align} 
= u
$ 


In [18]:
weights = np.array([0.5, 0.3, 0.1, 0.08, 0.02])
values = np.arange(10).reshape(5, -1)
weights.shape, values.shape

((5,), (5, 2))

In [19]:
np.dot(weights, values)

array([1.64, 2.64])

####Ex) A, B, C 세 회사의 주식은 각각 80만원, 30만원, 40만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하기.

In [22]:
vector_w = np.array([[80], [30], [40]])
vector_x = np.array([[3], [4], [5]])
vector_w.T.shape, vector_x.shape

((1, 3), (3, 1))

In [23]:
vector_w.T @ vector_x

array([[560]])

###가중평균(weighted average) : 가중합의 가중치값을 전체 가중치값 합으로 나누는 것.
$
\begin{align}
  \bar{x} = \frac{1}{N} \sum_{𝑖=1}^𝑁𝑥_𝑖 = \frac{1}{𝑁}1^𝑇_𝑁𝑥
\end{align} 
$ 

In [35]:
x = np.arange(10)
N = len(x)

np.ones(N) @ x / N, x.mean()

(4.5, 4.5)

####Ex) 대학 평균 성적 계산 : 1학점과 3학점 과목의 점수가 A 학생이 각각 100점, 60점이면 학점
$ 
\begin{align}
  \frac{1}{1+3}×100+ \frac{3}{1+3}×60=70 
\end{align}
$

In [39]:
each_score_weighteds = np.array([[1], [3]])
each_scores = np.array([[100], [60]])
weighted_total = each_score_weighteds.sum()
each_scores, each_score_weighteds, weighted_total, 

(array([[100],
        [ 60]]), array([[1],
        [3]]), 4)

In [42]:
each_score_weighteds.T @ each_scores / weighted_total, each_scores.mean()

(array([[70.]]), 80.0)

####Ex) 위 조건으로 A 학생이 100점/60점이면 학점, B학생이 95점/75점, C학생이 85점/70점인 경우 각각 학점 구하기. 


In [46]:
each_scores = np.array([[100, 60]
                        ,[95, 75]
                        ,[85, 70]])
each_score_weighteds.shape, each_scores.shape

((2, 1), (3, 2))

In [48]:
each_scores @ each_score_weighteds / weighted_total, each_scores.mean(axis=1)

(array([[70.  ],
        [80.  ],
        [73.75]]), array([80. , 85. , 77.5]))