<a href="https://colab.research.google.com/github/SanghunOh/with_mathematics/blob/main/codes/LinearAlgebra_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%98%95%ED%83%9C%EA%B0%84%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###벡터와 행렬도 숫자처럼 덧셈, 뺄셈, 곱셈 등의 연산 가능, 사칙연산과 다른 점 이해

##벡터/행렬 덧셈과 뺄셈 : 같은 크기를 가진 두 개 벡터나 행렬이 조건. 원소끼리 연산을 요소별(element-wise) 연산이라 함.
- Vector \\
$
\begin{align}
  x = \begin{pmatrix}
  1 \\ 2 \\ 3 
  \end{pmatrix}
  , y = \begin{pmatrix}
  4 \\ 6 \\ 8 
  \end{pmatrix}
\end{align} 
$ 
  - x - y \\
$
\begin{align}
  x = \begin{pmatrix}
  1 \\ 2 \\ 3 
  \end{pmatrix}
  + y = \begin{pmatrix}
  4 \\ 6 \\ 8 
  \end{pmatrix}
  = \begin{pmatrix}
  1-4 \\ 2-6 \\ 3-8 
  \end{pmatrix}
  = \begin{pmatrix}
  -3 \\ -4 \\ -5 
  \end{pmatrix}
\end{align} 
$ 
- Matrix 
  - x - y

In [3]:
import numpy as np
vector_1 = np.arange(3).reshape(1,-1)
vector_2 = np.arange(start=4,stop=9,step=2).reshape(1,-1)

vector_1, vector_2

(array([[0, 1, 2]]), array([[4, 6, 8]]))

In [4]:
vector_1 + vector_2

array([[ 4,  7, 10]])

In [5]:
vector_1 - vector_2

array([[-4, -5, -6]])

In [6]:
matrix_1 = np.arange(6).reshape(2,-1)
matrix_2 = np.arange(start=7,stop=19,step=2).reshape(2,-1)
matrix_1, matrix_2

(array([[0, 1, 2],
        [3, 4, 5]]), array([[ 7,  9, 11],
        [13, 15, 17]]))

In [7]:
matrix_1 - matrix_2

array([[ -7,  -8,  -9],
       [-10, -11, -12]])

In [8]:
matrix_1 + matrix_2

array([[ 7, 10, 13],
       [16, 19, 22]])

##스칼라와 벡터/행렬의 곱셈 : 모든 원소에 스칼라(scale)값 constant를 곱하는 것과 같음.
- Vector \\
$
\begin{align}
  constant \begin{pmatrix}
  x_1 \\ x_2 \\ ... \\ x_n
  \end{pmatrix}
\end{align} 
$ 
$ 
\begin{align}
  = \begin{pmatrix}
  constant \times x_1 \\ constant \times x_2 \\ ... \\ constant \times x_n
  \end{pmatrix}
\end{align} 
$
- Matrix \\
$
\begin{align}
  constant \begin{pmatrix}
  x_{1,1} & x_{1,2} & x_{1,3} \\
  x_{2,1} & x_{2,2} & x_{2,3}
  \end{pmatrix}
\end{align} 
$ 
$
\begin{align}
= \begin{pmatrix}
  constant \times x_{1,1} & constant \times x_{1,2} & constant \times x_{1,3} \\
  constant \times x_{2,1} & constant \times x_{2,2} & constant \times x_{2,3}
  \end{pmatrix}
\end{align} 
$ 


In [9]:
constant = 2

In [10]:
vector_3 = np.arange(3).reshape(3, -1)
vector_3.shape

(3, 1)

In [15]:
constant % vector_3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[0],
       [0],
       [0]])

In [14]:
vector_3 // constant

array([[0],
       [0],
       [1]])

##브로드캐스팅 : 덧셈과 뺄셈은 크기(차원)가 같은 두 벡터에 대해서만 할 수 있지만, 벡터와 스칼라의 경우에는 스칼라를 벡터로 변환한 연산을 허용.
- Vector \\
$
\begin{align}
  constant - \begin{pmatrix}
  x_1 \\ x_2 \\ ... \\ x_n
  \end{pmatrix}
\end{align} 
$ 
$ 
\begin{align}
  = \begin{pmatrix}
  constant \\ constant \\ ... \\ constant
  \end{pmatrix}
  - \begin{pmatrix}
  x_1 \\ x_2 \\ ... \\ x_n
  \end{pmatrix}
\end{align} 
$


In [17]:
constant, vector_3

(2, array([[0],
        [1],
        [2]]))

In [18]:
constant - vector_3

array([[2],
       [1],
       [0]])