<a href="https://colab.research.google.com/github/SanghunOh/with_mathematics/blob/main/codes/LinearAlgebra_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%98%95%ED%83%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##스칼라(scalar) : 하나에 숫자
$ 𝑥∈𝐑 $

##벡터(vector) : 여러 개 숫자 묶음. 특징 자세히 설명 가능(특징 벡터, feature vector).
$
\begin{align}
       x = 𝑥⃗ = \begin{pmatrix}
        x_1 \\ x_2 \\ x_3 \\ ... \\ x_n
        \end{pmatrix}
    \end{align} 
$ 
$ 
\begin{align}
       = \begin{pmatrix}
        x_1 & x_2 & x_3 & ... & x_n
        \end{pmatrix}
    \end{align} 
$
$ = 𝑥 ∈ 𝐑^n $ 

#### 구현 시 주의 사항
vector_1과 vector_2은 같이 다루나, 패키지 따라 구별됨(ex. sklearn 입력 형태 등)

In [3]:
#하나 vector이면서 2차원 배열(2-dimensional array)
import numpy as np
vector_1 = np.array([[5.1], [3.5], [1.4], [0.2]])
vector_1

array([[5.1],
       [3.5],
       [1.4],
       [0.2]])

In [5]:
#하나 vector이면서 1차원 배열(1-dimensional array)
vector_2 = np.array([5.1, 3.5, 1.4, 0.2])
vector_2

array([5.1, 3.5, 1.4, 0.2])

In [1]:
from sklearn.datasets import load_iris  # 사이킷런 패키지

iris = load_iris()  # 데이터 로드
iris.data[0, :]  # 첫 번째 꽃의 데이터

array([5.1, 3.5, 1.4, 0.2])

##행렬(matrix)

##1

##텐서(tensor)