<a href="https://colab.research.google.com/github/SanghunOh/with_mathematics/blob/main/codes/LinearAlgebra_%EC%84%A0%ED%98%95%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##[역행렬(inverse matrix)](https://datascienceschool.net/02%20mathematics/02.04%20%EC%84%A0%ED%98%95%20%EC%97%B0%EB%A6%BD%EB%B0%A9%EC%A0%95%EC%8B%9D%EA%B3%BC%20%EC%97%AD%ED%96%89%EB%A0%AC.html#id3) : 행렬에서 나눗셈, 원래 정방 행렬 𝐴와 아래 관계를 만족하는 행렬.
$ 𝐴^{−1}𝐴=𝐴𝐴^{−1}=𝐼 $

In [14]:
import numpy as np

matrix_A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
matrix_A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [15]:
np.linalg.inv(matrix_A)

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

###역행렬 존재 여부 : det(𝐴)=0이면 역수이 없음. 행렬식이 0이 아닌 경우에만 존재
$
𝐴^{−1}=\frac{1}{det(𝐴)}𝐶^𝑇
$
- 역행렬이 존재 : 가역행렬(invertible matrix), 정칙행렬(regular matrix) 또는 비특이행렬(non-singular matrix)이라 함. 
- 역행렬이 없는 행렬 : 비가역행렬(non-invertible matrix) 또는 특이행렬(singular matrix), 퇴화행렬(degenerate matrix)이라 함.


### 역행렬 구하기
$
\begin{align}
  \begin{pmatrix}
    \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \\
    \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
  \end{pmatrix}
\end{align} 
$

##[역행렬에 대한 정리](https://datascienceschool.net/02%20mathematics/02.04%20%EC%84%A0%ED%98%95%20%EC%97%B0%EB%A6%BD%EB%B0%A9%EC%A0%95%EC%8B%9D%EA%B3%BC%20%EC%97%AD%ED%96%89%EB%A0%AC.html#id10) : skip

##선형 연립방정식(system of linear equations) 또는 연립일차방정식 : 여러 미지수를 포함하는 선형 방정식 
$
\begin{align}
  a_{11}x_1 + a_{12}x_2 + ... + a_{1M}x_M = b_1 \\
  a_{21}x_1 + a_{22}x_2 + ... + a_{1M}x_M = b_2 \\
   ...  \\
  a_{N1}x_1 + a_{N2}x_2 + ... + a_{NM}x_M = b_N \\
\end{align} 
$

위 식은 아래와 같이 각각 계수행렬(coefficient matrix), 미지수벡터(unknown vector), 상수벡터(constant vector) 표현 가능 \\

$
\begin{align}
  \begin{pmatrix}
    a_{11} & a_{12} & ... & a_{1M} \\
    a_{21} & a_{22} & ... & a_{2M} \\
    ... \\
    a_{N1} & a_{N2} & ... & a_{NM} \\
  \end{pmatrix}
  \begin{pmatrix}
    x_1 \\
    x_2 \\
    ... \\
    x_M \\
  \end{pmatrix}
  =
  \begin{pmatrix}
    b_1 \\
    b_2 \\
    ... \\
    b_M \\
  \end{pmatrix}
\end{align} 
$

ex) 
$
x_1 + x_2 = 2 \\
x_2 + x_3 = 2 \\
x_1 + x_3 = 3 \\
$

$
\begin{align}
  \begin{pmatrix}
    1 & 1 & 0 \\
    0 & 1 & 1 \\
    1 & 0 & 1 \\
  \end{pmatrix}
  \begin{pmatrix}
    x_1 \\
    x_2 \\
    ... \\
    x_M \\
  \end{pmatrix}
  =
  \begin{pmatrix}
    2 \\
    2 \\
    3 \\
  \end{pmatrix}
\end{align} 
$

##역행렬과 선형 연립방정식의 해 : 미지수의 수와 방정식의 수가 같다면 계수행렬 𝐴는 정방행렬
- 역행렬 정의로 선형 연립 방정식 해 구하는 유도 과정

$
𝐴𝑥=𝑏 \\
𝐴^{−1}𝐴𝑥=𝐴^{−1}𝑏 \\
𝐼𝑥=𝐴^{−1}𝑏 \\
𝑥=𝐴^{−1}𝑏
$

In [16]:
matrix_b = np.array([[2], [2], [3]])
matrix_x = np.linalg.inv(matrix_A) @ matrix_b
matrix_x

array([[1.],
       [1.],
       [1.]])

In [17]:
# 연립방정식에 대입하여 상수벡터 𝑏와 값이 일치하는지 확인
matrix_A @ matrix_x - matrix_b

array([[0.],
       [0.],
       [0.]])

##[선형 예측모형](https://datascienceschool.net/02%20mathematics/02.04%20%EC%84%A0%ED%98%95%20%EC%97%B0%EB%A6%BD%EB%B0%A9%EC%A0%95%EC%8B%9D%EA%B3%BC%20%EC%97%AD%ED%96%89%EB%A0%AC.html#id14) : 가중치벡터 𝑤를 찾는 것
$ 𝑤=𝑋^{−1}𝑦 $
- 계수행렬이 𝑋, 미지수벡터가 𝑤, 상수벡터가 𝑦

In [ ]:
from sklearn.datasets import load_boston
boston = load_boston()
datas = boston.data
targets = boston.target
X = datas[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
y = targets[:4]

In [25]:
X, y

(array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
        [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
        [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
        [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]]),
 array([24. , 21.6, 34.7, 33.4]))

In [26]:
weights = np.linalg.inv(X) @ y
weights

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [28]:
np.round(X @ weights - y, 1)

array([0., 0., 0., 0.])

##선형 연립방정식의 해가 존재하지 않을 때 이슈
- 방정식의 수가 미지수의 수보다 적다. (𝑁<𝑀) → 무수히 많은 해
- 방정식의 수가 미지수의 수보다 많다. (𝑁>𝑀) → 해가 없음
### 해결법 : 좌변과 우변의 차이를 최소화하는 문제로 바꾸어 구함.
$ 𝐴𝑥≈𝑏 $

###[최소자승문제](https://datascienceschool.net/02%20mathematics/02.04%20%EC%84%A0%ED%98%95%20%EC%97%B0%EB%A6%BD%EB%B0%A9%EC%A0%95%EC%8B%9D%EA%B3%BC%20%EC%97%AD%ED%96%89%EB%A0%AC.html#id17)
- 예측값과 목푯값의 차이를 잔차(residual)를 최소화  
- 잔차(e)는 벡터이므로 최소자승문제에서는 벡터 크기 중에서 벡터 놈(norm)을 최소화 구하기
$ 𝑒^𝑇𝑒=‖𝑒‖^2=(𝐴𝑥−𝑏)^𝑇(𝐴𝑥−𝑏) → $
$ 𝑥=argmin_𝑥 𝑒^𝑇𝑒=argmin_𝑥(𝐴𝑥−𝑏)^𝑇(𝐴𝑥−𝑏) $

####과정 : 의사역행렬(pseudo\ inverse) - $ 𝐴^+=(𝐴^𝑇𝐴)^{−1}𝐴^𝑇 $
$ 
𝐴𝑥≈𝑏 \\
𝐴^𝑇𝐴𝑥=𝐴^𝑇𝑏 \\
(𝐴^𝑇𝐴)^{−1}(𝐴^𝑇𝐴)𝑥=(𝐴^𝑇𝐴)^{−1}𝐴^𝑇𝑏 → 𝐴^𝑇𝐴 역행렬 존재 시 \\
𝑥=((𝐴^𝑇𝐴)^{−1}𝐴^𝑇)𝑏 \\
𝑥=𝐴^+𝑏
$

In [29]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [30]:
b = np.array([[2], [2], [3], [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [31]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [32]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [33]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [18]:
# tip : lstsq() better then inv() 
matrix_x, residual, rank, singular_value = np.linalg.lstsq(matrix_A, matrix_b)
matrix_x, residual, rank, singular_value

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


(array([[1.],
        [1.],
        [1.]]),
 array([], dtype=float64),
 3,
 array([2.41421356, 1.        , 0.41421356]))

In [34]:
x, residual, rank, singular_value = np.linalg.lstsq(A, b)
x, residual, rank, singular_value

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([[1.03333333],
        [0.95      ],
        [1.05      ]]),
 array([0.00166667]),
 3,
 array([3.35753997, 1.15123198, 0.6337115 ]))

In [35]:
# 잔차벡터의 𝑒=𝐴𝑥−𝑏의 제곱합, 즉 놈의 제곱
residual, np.linalg.norm(A @ x - b) ** 2

(array([0.00166667]), 0.0016666666666666624)

##보스턴 집값 문제를 선형 예측모형 𝑋𝑤=𝑦̂ 로 풀었을 때의 가중치벡터 𝑤를 최소 자승 방법으로 구하라